### ISSUE TITLE
Reusing keys with arrays of tables does not result in an error

### ISSUE THREAD

**Issue by BinaryMuse** [BinaryMuse/toml-node#10]
``` toml
[[a]]
first = 1

 [a.b]
   second = 2

 [[a.b]]
   third = 3
```

`a.b` is, correctly, not reassigned, but no error is thrown.
