### ISSUE TITLE
If first line is empty, passed failed

### ISSUE THREAD

**Issue by fundon** [BinaryMuse/toml-node#22]
```
Error: Error parsing your configuration file: [/Users/fundon/dev/trekjs/trek/test/fixtures/config/app.test.toml]: Expected "#", "[", [ \t] or end of input but "\n" found..
```

```toml

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
organization = "GitHub"
bio = "GitHub Cofounder & CEO\n\tLikes \"tater tots\" and beer and backslashes: \\"
dob = 1979-05-27T07:32:00Z # First class dates? Why not?

```
