### ISSUE TITLE
Backslashes may ONLY precede valid escapes, pre the spec.

### ISSUE THREAD

**Issue by iarna** [BinaryMuse/toml-node#49]
This appears to have been introduced by: https://github.com/BinaryMuse/toml-node/issues/21

To sum up the problem:

Given the following TOML: 

```toml
["the\ key"]

one = "one"
two = 2
three = false
```

This library produces:

``` json
{"the\\ key":{"one":"one","two":2,"three":false}}
```

In contrast, it should produce an error, per the spec:

> All other escape sequences not listed above are reserved and, if used, TOML should produce an error.

Restoring this to an error would make this library's behavior consistent with toml-j0.4 and @iarna/toml.

Valid TOML with a slash in the key name would be either of these:

```toml
["the\\ key"]

one = "one"
two = 2
three = false
```

or

```toml
['the\ key']

one = "one"
two = 2
three = false
```
